### ISSUE TITLE
域名管理简介中应增加域名解析服务的相关链接

### ISSUE THREAD

**Issue by yixiaoer2012** [huaweicloudDocs/domains#1]
域名管理与域名解析服务关系非常紧密，简介中除了现有界面中的操作外，应增加域名解析服务的相关链接

**Comment by MeetZY001** [comment]
文档提到华为云域名注册服务支持查看已注册域名的注册信息（WHOIS），但是没有给出华为云Whois平台的地址。建议增加华为云Whois平台的地址，便于用于快速定位到位置

**Comment by chengnan6** [comment]
> 域名管理与域名解析服务关系非常紧密，简介中除了现有界面中的操作外，应增加域名解析服务的相关链接

在域名的如下章节均已增加了到域名解析相关操作或页面的链接：
1、什么是域名注册服务
2、入门指引
3、配置网站解析
