### ISSUE TITLE
查看域名注册信息（WHOIS）缺少链接

### ISSUE THREAD

**Issue by MeetZY001** [huaweicloudDocs/domains#2]
文档提到华为云域名注册服务支持查看已注册域名的注册信息（WHOIS），但是没有给出华为云Whois平台的地址。建议增加华为云Whois平台的地址，便于用于快速定位到位置

**Comment by chengnan6** [comment]
> 文档提到华为云域名注册服务支持查看已注册域名的注册信息（WHOIS），但是没有给出华为云Whois平台的地址。建议增加华为云Whois平台的地址，便于用于快速定位到位置

已增加华为云Whois平台的链接：
![image](https://user-images.githubusercontent.com/58577979/133869810-05c3fe46-e100-426e-841c-f447e5e08a3e.png)
